### ISSUE TITLE
Graceful recovery from premature EOF

### ISSUE THREAD

**Issue by lunabunn** [bschwind/png-decoder#19]
I was trying to decode this image using `png-decoder`
![forestDecoration_0](https://user-images.githubusercontent.com/29861658/194730563-1945549b-9c3b-42bf-8444-7cf0e4af41e3.png)
but got an `Err(MissingBytes)`.

Upon closer inspection, it appears that the image has an extra zero byte at the end for whatever reason, causing `png-decoder` to hit a premature EOF and fail to decode the image. Opening up the image in a hex editor and removing that byte resolves the issue.

Would it be within the scope of this crate to try and gracefully recover from small errors like these, or does it only intend to support to-spec PNGs?

**Comment by bschwind** [comment]
Thanks for reporting this!

I think this can be solved by detecting the `ImageEnd` chunk and ignoring further bytes after that, but let me double check my assumptions on that.

**Comment by bschwind** [comment]
@lunabunn do you mind if I add that image as a test image for this repository?

**Comment by lunabunn** [comment]
> @lunabunn do you mind if I add that image as a test image for this repository?

The image is actually not mine, but it's a free asset from https://analogstudios.itch.io/forest that is licensed under CC-0, so it should be fine.

Thank you for the quick response!

**Comment by bschwind** [comment]
@lunabunn version 0.1.1 is now published with the fix for this issue

**Comment by lunabunn** [comment]
Thanks!
